### ISSUE TITLE
About self.indices

### ISSUE THREAD

**Issue by ljhOfGithub** [mahmoodlab/MCAT#11]
In the class SubsetSequentialSampler,the indices should be iterable,but I get a variable of numpy.int64.My torch version is 2.0.1.And my python version is 3.9.How could I solve the problem?
This is my whole traceback:
```
Traceback (most recent call last):
  File "/mnt/data0/LI_jihao/mydata/MCAT-master/main.py", line 199, in <module>
    dataset = Generic_MIL_Survival_Dataset(csv_path = '/home/jupyter-ljh/data/mydata/MCAT-master/dataset_csv/tcga_brca_all_clean.csv',
  File "/mnt/data0/LI_jihao/mydata/MCAT-master/main.py", line 71, in main
    val_latest, cindex_latest = train(datasets, i, args)
  File "/mnt/data0/LI_jihao/mydata/MCAT-master/utils/core_utils.py", line 181, in train
    for i,data in enumerate(train_loader):
  File "/opt/tljh/user/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/opt/tljh/user/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 676, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/opt/tljh/user/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 623, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/opt/tljh/user/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 254, in __iter__
    for idx in self.sampler:
  File "/mnt/data0/LI_jihao/mydata/MCAT-master/utils/utils.py", line 36, in __iter__
    return iter(self.indices)
TypeError: 'numpy.int64' object is not iterable
```

**Comment by ljhOfGithub** [comment]
See #9.
